### ISSUE TITLE
Enable dirlisting on the public repository

### ISSUE THREAD

**Issue by Nowaker** [selwtf/turris#16]
I'd like to browse https://storage.googleapis.com/sel-wtf-turris/omnia/stable/packages myself to see what exactly is hosted there before I add a repository to my system.

**Comment by DanielSel** [comment]
Unfortunately, directory listing is not available with GCS Buckets.
However, you can download the "Packages" file from each directory, which will contain a list of all packages + metadata.
E.g.: https://storage.googleapis.com/sel-wtf-turris/omnia/stable/packages/Packages
